# Generated by Django 4.1.7 on 2023-07-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_assignments_delete_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(max_length=1000)),
                ('assignments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_assgnd', to='home.assignments')),
            ],
            options={
                'db_table': 'remarks',
            },
        ),
    ]
