# Generated by Django 4.1.7 on 2023-07-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
