# Generated by Django 4.1.7 on 2023-07-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_assignments_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Remarks',
        ),
    ]
