# Generated by Django 4.1.7 on 2023-07-17 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_assignments_active_delete_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assgnd_date',
            field=models.DateField(default=datetime.date(2023, 7, 17)),
        ),
        migrations.AddField(
            model_name='assignments',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='removed_date',
            field=models.DateField(null=True),
        ),
    ]
