# Generated by Django 4.1.7 on 2023-07-17 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_assignments_assgnd_date_assignments_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assgnd_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
